wget -c https://www.encodeproject.org/files/ENCFF813IAR/@@download/ENCFF813IAR.bed.gz -O "W3L_IDR/N_ENCFF813IAR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF618BGI/@@download/ENCFF618BGI.bed.gz -O "W3L_IDR/usp_ENCFF618BGI.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF254GBE/@@download/ENCFF254GBE.bed.gz -O "W3L_IDR/Dif_ENCFF254GBE.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF828LRJ/@@download/ENCFF828LRJ.bed.gz -O "W3L_IDR/br_ENCFF828LRJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF326UHJ/@@download/ENCFF326UHJ.bed.gz -O "W3L_IDR/Mondo_ENCFF326UHJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF370YJF/@@download/ENCFF370YJF.bed.gz -O "W3L_IDR/GATAd_ENCFF370YJF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF007DSW/@@download/ENCFF007DSW.bed.gz -O "W3L_IDR/sv_ENCFF007DSW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF168FQF/@@download/ENCFF168FQF.bed.gz -O "W3L_IDR/Vsx2_ENCFF168FQF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF595FXC/@@download/ENCFF595FXC.bed.gz -O "W3L_IDR/OdsH_ENCFF595FXC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF153PUC/@@download/ENCFF153PUC.bed.gz -O "W3L_IDR/lola_ENCFF153PUC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF475UCX/@@download/ENCFF475UCX.bed.gz -O "W3L_IDR/Hr83_ENCFF475UCX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF791NME/@@download/ENCFF791NME.bed.gz -O "W3L_IDR/SREBP_ENCFF791NME.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF450DOL/@@download/ENCFF450DOL.bed.gz -O "W3L_IDR/dsf_ENCFF450DOL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF999IMC/@@download/ENCFF999IMC.bed.gz -O "W3L_IDR/tai_ENCFF999IMC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF980AQF/@@download/ENCFF980AQF.bed.gz -O "W3L_IDR/mod(mdg4)_ENCFF980AQF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF762NWS/@@download/ENCFF762NWS.bed.gz -O "W3L_IDR/psq_ENCFF762NWS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF983OXZ/@@download/ENCFF983OXZ.bed.gz -O "W3L_IDR/psq_ENCFF983OXZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF623RDH/@@download/ENCFF623RDH.bed.gz -O "W3L_IDR/psq_ENCFF623RDH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF471JEZ/@@download/ENCFF471JEZ.bed.gz -O "W3L_IDR/Dif_ENCFF471JEZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF192OFW/@@download/ENCFF192OFW.bed.gz -O "W3L_IDR/h_ENCFF192OFW.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF982SAT/@@download/ENCFF982SAT.bed.gz -O "W3L_IDR/fru_ENCFF982SAT.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF393QNM/@@download/ENCFF393QNM.bed.gz -O "W3L_IDR/foxo_ENCFF393QNM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF330FMC/@@download/ENCFF330FMC.bed.gz -O "W3L_IDR/Hnf4_ENCFF330FMC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF577PBK/@@download/ENCFF577PBK.bed.gz -O "W3L_IDR/N_ENCFF577PBK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF126COV/@@download/ENCFF126COV.bed.gz -O "W3L_IDR/OdsH_ENCFF126COV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF351JBY/@@download/ENCFF351JBY.bed.gz -O "W3L_IDR/cnc_ENCFF351JBY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF062RMB/@@download/ENCFF062RMB.bed.gz -O "W3L_IDR/h_ENCFF062RMB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF590MOM/@@download/ENCFF590MOM.bed.gz -O "W3L_IDR/Rel_ENCFF590MOM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF558TGI/@@download/ENCFF558TGI.bed.gz -O "W3L_IDR/lola_ENCFF558TGI.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF834CPL/@@download/ENCFF834CPL.bed.gz -O "W3L_IDR/jim_ENCFF834CPL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF268RAU/@@download/ENCFF268RAU.bed.gz -O "W3L_IDR/noc_ENCFF268RAU.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF700CSS/@@download/ENCFF700CSS.bed.gz -O "W3L_IDR/Dif_ENCFF700CSS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF711IFR/@@download/ENCFF711IFR.bed.gz -O "W3L_IDR/mod(mdg4)_ENCFF711IFR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF387YJY/@@download/ENCFF387YJY.bed.gz -O "W3L_IDR/CG32264_ENCFF387YJY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF827RGK/@@download/ENCFF827RGK.bed.gz -O "W3L_IDR/Jra_ENCFF827RGK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF910XQH/@@download/ENCFF910XQH.bed.gz -O "W3L_IDR/Myc_ENCFF910XQH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF047ZPF/@@download/ENCFF047ZPF.bed.gz -O "W3L_IDR/CG32264_ENCFF047ZPF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF560HVJ/@@download/ENCFF560HVJ.bed.gz -O "W3L_IDR/Rel_ENCFF560HVJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF729UYT/@@download/ENCFF729UYT.bed.gz -O "W3L_IDR/dsf_ENCFF729UYT.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF223DXV/@@download/ENCFF223DXV.bed.gz -O "W3L_IDR/CrebA_ENCFF223DXV.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF135YRC/@@download/ENCFF135YRC.bed.gz -O "W3L_IDR/Mondo_ENCFF135YRC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF127TCW/@@download/ENCFF127TCW.bed.gz -O "W3L_IDR/Rel_ENCFF127TCW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF390FWQ/@@download/ENCFF390FWQ.bed.gz -O "W3L_IDR/cnc_ENCFF390FWQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF525QZM/@@download/ENCFF525QZM.bed.gz -O "W3L_IDR/Abd-B_ENCFF525QZM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF431AXM/@@download/ENCFF431AXM.bed.gz -O "W3L_IDR/fru_ENCFF431AXM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF465TPE/@@download/ENCFF465TPE.bed.gz -O "W3L_IDR/ey_ENCFF465TPE.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF857SSH/@@download/ENCFF857SSH.bed.gz -O "W3L_IDR/Jra_ENCFF857SSH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF473JDK/@@download/ENCFF473JDK.bed.gz -O "W3L_IDR/usp_ENCFF473JDK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF321OSN/@@download/ENCFF321OSN.bed.gz -O "W3L_IDR/Abd-B_ENCFF321OSN.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF763JRO/@@download/ENCFF763JRO.bed.gz -O "W3L_IDR/lola_ENCFF763JRO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF949QAM/@@download/ENCFF949QAM.bed.gz -O "W3L_IDR/usp_ENCFF949QAM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF209DSJ/@@download/ENCFF209DSJ.bed.gz -O "W3L_IDR/lola_ENCFF209DSJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF351IVD/@@download/ENCFF351IVD.bed.gz -O "W3L_IDR/Hr78_ENCFF351IVD.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF520HSE/@@download/ENCFF520HSE.bed.gz -O "W3L_IDR/brk_ENCFF520HSE.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF894XOC/@@download/ENCFF894XOC.bed.gz -O "W3L_IDR/sage_ENCFF894XOC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF054XII/@@download/ENCFF054XII.bed.gz -O "W3L_IDR/dsf_ENCFF054XII.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF050QUA/@@download/ENCFF050QUA.bed.gz -O "W3L_IDR/fru_ENCFF050QUA.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF500ODO/@@download/ENCFF500ODO.bed.gz -O "W3L_IDR/jim_ENCFF500ODO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF910ZAF/@@download/ENCFF910ZAF.bed.gz -O "W3L_IDR/rgr_ENCFF910ZAF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF966JNW/@@download/ENCFF966JNW.bed.gz -O "W3L_IDR/tai_ENCFF966JNW.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF494BCB/@@download/ENCFF494BCB.bed.gz -O "W3L_IDR/Dfd_ENCFF494BCB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF488FWS/@@download/ENCFF488FWS.bed.gz -O "W3L_IDR/Abd-B_ENCFF488FWS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF202YXL/@@download/ENCFF202YXL.bed.gz -O "W3L_IDR/GATAd_ENCFF202YXL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF400LCF/@@download/ENCFF400LCF.bed.gz -O "W3L_IDR/br_ENCFF400LCF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF449WFM/@@download/ENCFF449WFM.bed.gz -O "W3L_IDR/pan_ENCFF449WFM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF048MUD/@@download/ENCFF048MUD.bed.gz -O "W3L_IDR/sv_ENCFF048MUD.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF165PAF/@@download/ENCFF165PAF.bed.gz -O "W3L_IDR/dl_ENCFF165PAF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF700KLJ/@@download/ENCFF700KLJ.bed.gz -O "W3L_IDR/sage_ENCFF700KLJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF121BWC/@@download/ENCFF121BWC.bed.gz -O "W3L_IDR/Hr83_ENCFF121BWC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF839BUX/@@download/ENCFF839BUX.bed.gz -O "W3L_IDR/br_ENCFF839BUX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF315KMW/@@download/ENCFF315KMW.bed.gz -O "W3L_IDR/Hnf4_ENCFF315KMW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF428MGH/@@download/ENCFF428MGH.bed.gz -O "W3L_IDR/SREBP_ENCFF428MGH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF371NVP/@@download/ENCFF371NVP.bed.gz -O "W3L_IDR/foxo_ENCFF371NVP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF295RNM/@@download/ENCFF295RNM.bed.gz -O "W3L_IDR/Jra_ENCFF295RNM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF658CAJ/@@download/ENCFF658CAJ.bed.gz -O "W3L_IDR/usp_ENCFF658CAJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF304QAQ/@@download/ENCFF304QAQ.bed.gz -O "W3L_IDR/GATAd_ENCFF304QAQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF265CHU/@@download/ENCFF265CHU.bed.gz -O "W3L_IDR/dl_ENCFF265CHU.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF101TBI/@@download/ENCFF101TBI.bed.gz -O "W3L_IDR/Rel_ENCFF101TBI.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF665ITW/@@download/ENCFF665ITW.bed.gz -O "W3L_IDR/CG9705_ENCFF665ITW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF130XNU/@@download/ENCFF130XNU.bed.gz -O "W3L_IDR/Hr83_ENCFF130XNU.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF746FSF/@@download/ENCFF746FSF.bed.gz -O "W3L_IDR/dl_ENCFF746FSF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF048PDV/@@download/ENCFF048PDV.bed.gz -O "W3L_IDR/lola_ENCFF048PDV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF686TUR/@@download/ENCFF686TUR.bed.gz -O "W3L_IDR/OdsH_ENCFF686TUR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF130FLY/@@download/ENCFF130FLY.bed.gz -O "W3L_IDR/Rel_ENCFF130FLY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF081XXK/@@download/ENCFF081XXK.bed.gz -O "W3L_IDR/cnc_ENCFF081XXK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF223LBB/@@download/ENCFF223LBB.bed.gz -O "W3L_IDR/Hr83_ENCFF223LBB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF233LHC/@@download/ENCFF233LHC.bed.gz -O "W3L_IDR/lola_ENCFF233LHC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF910TTJ/@@download/ENCFF910TTJ.bed.gz -O "W3L_IDR/Sp1_ENCFF910TTJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF106QQM/@@download/ENCFF106QQM.bed.gz -O "W3L_IDR/woc_ENCFF106QQM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF420IED/@@download/ENCFF420IED.bed.gz -O "W3L_IDR/br_ENCFF420IED.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF582WMX/@@download/ENCFF582WMX.bed.gz -O "W3L_IDR/dl_ENCFF582WMX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF601OGS/@@download/ENCFF601OGS.bed.gz -O "W3L_IDR/Rel_ENCFF601OGS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF692SZZ/@@download/ENCFF692SZZ.bed.gz -O "W3L_IDR/ey_ENCFF692SZZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF594EHD/@@download/ENCFF594EHD.bed.gz -O "W3L_IDR/pan_ENCFF594EHD.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF076JKI/@@download/ENCFF076JKI.bed.gz -O "W3L_IDR/CG9705_ENCFF076JKI.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF407SLK/@@download/ENCFF407SLK.bed.gz -O "W3L_IDR/lola_ENCFF407SLK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF485DOS/@@download/ENCFF485DOS.bed.gz -O "W3L_IDR/GATAd_ENCFF485DOS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF916ZJW/@@download/ENCFF916ZJW.bed.gz -O "W3L_IDR/woc_ENCFF916ZJW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF021DTO/@@download/ENCFF021DTO.bed.gz -O "W3L_IDR/mod(mdg4)_ENCFF021DTO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF431ENP/@@download/ENCFF431ENP.bed.gz -O "W3L_IDR/Rel_ENCFF431ENP.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF338NBQ/@@download/ENCFF338NBQ.bed.gz -O "W3L_IDR/pan_ENCFF338NBQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF239FDP/@@download/ENCFF239FDP.bed.gz -O "W3L_IDR/sv_ENCFF239FDP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF561XEL/@@download/ENCFF561XEL.bed.gz -O "W3L_IDR/psq_ENCFF561XEL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF231PMD/@@download/ENCFF231PMD.bed.gz -O "W3L_IDR/br_ENCFF231PMD.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF837SDB/@@download/ENCFF837SDB.bed.gz -O "W3L_IDR/cnc_ENCFF837SDB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF357FPP/@@download/ENCFF357FPP.bed.gz -O "W3L_IDR/Rel_ENCFF357FPP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF771TSV/@@download/ENCFF771TSV.bed.gz -O "W3L_IDR/psq_ENCFF771TSV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF351MDY/@@download/ENCFF351MDY.bed.gz -O "W3L_IDR/br_ENCFF351MDY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF512SBV/@@download/ENCFF512SBV.bed.gz -O "W3L_IDR/Rel_ENCFF512SBV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF711CFY/@@download/ENCFF711CFY.bed.gz -O "W3L_IDR/CrebA_ENCFF711CFY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF513HGZ/@@download/ENCFF513HGZ.bed.gz -O "W3L_IDR/foxo_ENCFF513HGZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF128MIC/@@download/ENCFF128MIC.bed.gz -O "W3L_IDR/Hnf4_ENCFF128MIC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF773IPQ/@@download/ENCFF773IPQ.bed.gz -O "W3L_IDR/rgr_ENCFF773IPQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF755YZY/@@download/ENCFF755YZY.bed.gz -O "W3L_IDR/foxo_ENCFF755YZY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF855JSX/@@download/ENCFF855JSX.bed.gz -O "W3L_IDR/dl_ENCFF855JSX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF197ZGH/@@download/ENCFF197ZGH.bed.gz -O "W3L_IDR/jim_ENCFF197ZGH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF611GCG/@@download/ENCFF611GCG.bed.gz -O "W3L_IDR/usp_ENCFF611GCG.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF647QJO/@@download/ENCFF647QJO.bed.gz -O "W3L_IDR/lola_ENCFF647QJO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF894WJK/@@download/ENCFF894WJK.bed.gz -O "W3L_IDR/OdsH_ENCFF894WJK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF063BSF/@@download/ENCFF063BSF.bed.gz -O "W3L_IDR/h_ENCFF063BSF.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF889JIG/@@download/ENCFF889JIG.bed.gz -O "W3L_IDR/Hr78_ENCFF889JIG.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF213OIV/@@download/ENCFF213OIV.bed.gz -O "W3L_IDR/foxo_ENCFF213OIV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF745XNP/@@download/ENCFF745XNP.bed.gz -O "W3L_IDR/Mondo_ENCFF745XNP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF285XTO/@@download/ENCFF285XTO.bed.gz -O "W3L_IDR/noc_ENCFF285XTO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF048AUF/@@download/ENCFF048AUF.bed.gz -O "W3L_IDR/CG32264_ENCFF048AUF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF664APQ/@@download/ENCFF664APQ.bed.gz -O "W3L_IDR/noc_ENCFF664APQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF700NXM/@@download/ENCFF700NXM.bed.gz -O "W3L_IDR/N_ENCFF700NXM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF961SOP/@@download/ENCFF961SOP.bed.gz -O "W3L_IDR/rgr_ENCFF961SOP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF501ZRP/@@download/ENCFF501ZRP.bed.gz -O "W3L_IDR/CG9705_ENCFF501ZRP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF433TRM/@@download/ENCFF433TRM.bed.gz -O "W3L_IDR/dsf_ENCFF433TRM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF588QQP/@@download/ENCFF588QQP.bed.gz -O "W3L_IDR/dl_ENCFF588QQP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF890KUV/@@download/ENCFF890KUV.bed.gz -O "W3L_IDR/psq_ENCFF890KUV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF284RTS/@@download/ENCFF284RTS.bed.gz -O "W3L_IDR/CrebA_ENCFF284RTS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF910EOZ/@@download/ENCFF910EOZ.bed.gz -O "W3L_IDR/woc_ENCFF910EOZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF846DBY/@@download/ENCFF846DBY.bed.gz -O "W3L_IDR/br_ENCFF846DBY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF187MRL/@@download/ENCFF187MRL.bed.gz -O "W3L_IDR/brk_ENCFF187MRL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF702HFM/@@download/ENCFF702HFM.bed.gz -O "W3L_IDR/dl_ENCFF702HFM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF412MGO/@@download/ENCFF412MGO.bed.gz -O "W3L_IDR/Myc_ENCFF412MGO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF099JSW/@@download/ENCFF099JSW.bed.gz -O "W3L_IDR/SREBP_ENCFF099JSW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF428OYI/@@download/ENCFF428OYI.bed.gz -O "W3L_IDR/cnc_ENCFF428OYI.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF386VVR/@@download/ENCFF386VVR.bed.gz -O "W3L_IDR/sage_ENCFF386VVR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF546RHW/@@download/ENCFF546RHW.bed.gz -O "W3L_IDR/fru_ENCFF546RHW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF539PBL/@@download/ENCFF539PBL.bed.gz -O "W3L_IDR/dmrt93B_ENCFF539PBL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF276FSI/@@download/ENCFF276FSI.bed.gz -O "W3L_IDR/Myc_ENCFF276FSI.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF379LSJ/@@download/ENCFF379LSJ.bed.gz -O "W3L_IDR/noc_ENCFF379LSJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF274ZTV/@@download/ENCFF274ZTV.bed.gz -O "W3L_IDR/SREBP_ENCFF274ZTV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF519FBM/@@download/ENCFF519FBM.bed.gz -O "W3L_IDR/sv_ENCFF519FBM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF648MOV/@@download/ENCFF648MOV.bed.gz -O "W3L_IDR/Sp1_ENCFF648MOV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF896BBA/@@download/ENCFF896BBA.bed.gz -O "W3L_IDR/fru_ENCFF896BBA.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF239XVM/@@download/ENCFF239XVM.bed.gz -O "W3L_IDR/N_ENCFF239XVM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF322NYB/@@download/ENCFF322NYB.bed.gz -O "W3L_IDR/sv_ENCFF322NYB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF793NCQ/@@download/ENCFF793NCQ.bed.gz -O "W3L_IDR/usp_ENCFF793NCQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF512VEX/@@download/ENCFF512VEX.bed.gz -O "W3L_IDR/dmrt93B_ENCFF512VEX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF154DBR/@@download/ENCFF154DBR.bed.gz -O "W3L_IDR/Mondo_ENCFF154DBR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF337DBL/@@download/ENCFF337DBL.bed.gz -O "W3L_IDR/dl_ENCFF337DBL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF386LWO/@@download/ENCFF386LWO.bed.gz -O "W3L_IDR/foxo_ENCFF386LWO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF729HCO/@@download/ENCFF729HCO.bed.gz -O "W3L_IDR/ey_ENCFF729HCO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF168YBQ/@@download/ENCFF168YBQ.bed.gz -O "W3L_IDR/Vsx2_ENCFF168YBQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF015ENX/@@download/ENCFF015ENX.bed.gz -O "W3L_IDR/psq_ENCFF015ENX.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF020TVZ/@@download/ENCFF020TVZ.bed.gz -O "W3L_IDR/foxo_ENCFF020TVZ.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF040KHQ/@@download/ENCFF040KHQ.bed.gz -O "W3L_IDR/pan_ENCFF040KHQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF954LYN/@@download/ENCFF954LYN.bed.gz -O "W3L_IDR/Hr78_ENCFF954LYN.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF102VYM/@@download/ENCFF102VYM.bed.gz -O "W3L_IDR/usp_ENCFF102VYM.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF290IPR/@@download/ENCFF290IPR.bed.gz -O "W3L_IDR/jim_ENCFF290IPR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF742LVH/@@download/ENCFF742LVH.bed.gz -O "W3L_IDR/lola_ENCFF742LVH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF251HNA/@@download/ENCFF251HNA.bed.gz -O "W3L_IDR/Dfd_ENCFF251HNA.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF710HFR/@@download/ENCFF710HFR.bed.gz -O "W3L_IDR/ey_ENCFF710HFR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF333PXS/@@download/ENCFF333PXS.bed.gz -O "W3L_IDR/psq_ENCFF333PXS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF922NXU/@@download/ENCFF922NXU.bed.gz -O "W3L_IDR/usp_ENCFF922NXU.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF425XRQ/@@download/ENCFF425XRQ.bed.gz -O "W3L_IDR/cnc_ENCFF425XRQ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF341QUK/@@download/ENCFF341QUK.bed.gz -O "W3L_IDR/Myc_ENCFF341QUK.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF412VYJ/@@download/ENCFF412VYJ.bed.gz -O "W3L_IDR/mod(mdg4)_ENCFF412VYJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF184BCY/@@download/ENCFF184BCY.bed.gz -O "W3L_IDR/dmrt93B_ENCFF184BCY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF882OYL/@@download/ENCFF882OYL.bed.gz -O "W3L_IDR/cnc_ENCFF882OYL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF318IJE/@@download/ENCFF318IJE.bed.gz -O "W3L_IDR/Dfd_ENCFF318IJE.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF078CKY/@@download/ENCFF078CKY.bed.gz -O "W3L_IDR/usp_ENCFF078CKY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF494JVA/@@download/ENCFF494JVA.bed.gz -O "W3L_IDR/psq_ENCFF494JVA.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF639EBZ/@@download/ENCFF639EBZ.bed.gz -O "W3L_IDR/rgr_ENCFF639EBZ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF137JGS/@@download/ENCFF137JGS.bed.gz -O "W3L_IDR/br_ENCFF137JGS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF574VKT/@@download/ENCFF574VKT.bed.gz -O "W3L_IDR/Vsx2_ENCFF574VKT.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF070XGJ/@@download/ENCFF070XGJ.bed.gz -O "W3L_IDR/cnc_ENCFF070XGJ.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF094TGW/@@download/ENCFF094TGW.bed.gz -O "W3L_IDR/psq_ENCFF094TGW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF827AXW/@@download/ENCFF827AXW.bed.gz -O "W3L_IDR/brk_ENCFF827AXW.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF578CYC/@@download/ENCFF578CYC.bed.gz -O "W3L_IDR/rgr_ENCFF578CYC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF888KQO/@@download/ENCFF888KQO.bed.gz -O "W3L_IDR/SREBP_ENCFF888KQO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF744RAY/@@download/ENCFF744RAY.bed.gz -O "W3L_IDR/CrebA_ENCFF744RAY.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF939PJL/@@download/ENCFF939PJL.bed.gz -O "W3L_IDR/foxo_ENCFF939PJL.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF199XFV/@@download/ENCFF199XFV.bed.gz -O "W3L_IDR/CG32264_ENCFF199XFV.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF685KDH/@@download/ENCFF685KDH.bed.gz -O "W3L_IDR/Dif_ENCFF685KDH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF115KVP/@@download/ENCFF115KVP.bed.gz -O "W3L_IDR/noc_ENCFF115KVP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF850FWS/@@download/ENCFF850FWS.bed.gz -O "W3L_IDR/br_ENCFF850FWS.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF976RXC/@@download/ENCFF976RXC.bed.gz -O "W3L_IDR/h_ENCFF976RXC.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF740MEO/@@download/ENCFF740MEO.bed.gz -O "W3L_IDR/Jra_ENCFF740MEO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF621ZGP/@@download/ENCFF621ZGP.bed.gz -O "W3L_IDR/Sp1_ENCFF621ZGP.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF045HYO/@@download/ENCFF045HYO.bed.gz -O "W3L_IDR/brk_ENCFF045HYO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF503JUH/@@download/ENCFF503JUH.bed.gz -O "W3L_IDR/foxo_ENCFF503JUH.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF370NSR/@@download/ENCFF370NSR.bed.gz -O "W3L_IDR/tai_ENCFF370NSR.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF675TYB/@@download/ENCFF675TYB.bed.gz -O "W3L_IDR/Vsx2_ENCFF675TYB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF100TDT/@@download/ENCFF100TDT.bed.gz -O "W3L_IDR/Hr78_ENCFF100TDT.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF418QIB/@@download/ENCFF418QIB.bed.gz -O "W3L_IDR/Sp1_ENCFF418QIB.bed.gz" &
wait
wget -c https://www.encodeproject.org/files/ENCFF608HRB/@@download/ENCFF608HRB.bed.gz -O "W3L_IDR/Abd-B_ENCFF608HRB.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF632XCO/@@download/ENCFF632XCO.bed.gz -O "W3L_IDR/tai_ENCFF632XCO.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF145EUD/@@download/ENCFF145EUD.bed.gz -O "W3L_IDR/dmrt93B_ENCFF145EUD.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF074RLF/@@download/ENCFF074RLF.bed.gz -O "W3L_IDR/woc_ENCFF074RLF.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF594VMN/@@download/ENCFF594VMN.bed.gz -O "W3L_IDR/pan_ENCFF594VMN.bed.gz" &
wget -c https://www.encodeproject.org/files/ENCFF174HXY/@@download/ENCFF174HXY.bed.gz -O "W3L_IDR/CG9705_ENCFF174HXY.bed.gz" &
